### ISSUE TITLE
more a question...

### ISSUE THREAD

**Issue by LewisAlex** [oozcitak/exiflibrary#52]
Hi there,  
I was wondering if the Save method I use to save a **ImageFile** after modifying the tags could not save correctly ?
If my readings are correct, there are no exception thrown nor boolean value showing the process wasn't successfuly completed ?
Actually, I was looking to test the result of saving my file (in a kinda loop of _n_ files) ?...

regards,

**Comment by oozcitak** [comment]
Any exceptions thrown while writing to the underlying `System.IO.Stream` should propagate to your application. They are not caught by the library.

**Comment by LewisAlex** [comment]
So, could I put the *Save* between a try-catch to be sure the process was
correctly executed ?

2018-04-03 4:10 GMT-04:00 Ozgur Ozcitak <notifications@github.com>:

**Comment by oozcitak** [comment]
Yes you can.

**Comment by LewisAlex** [comment]
Great !
Big thnx !!

Le mer. 4 avr. 2018 16:54, Ozgur Ozcitak <notifications@github.com> a
écrit :
