### ISSUE TITLE
Function ImageFile.FromFile() not worked in Framework 4.7.1

### ISSUE THREAD

**Issue by fialot** [oozcitak/exiflibrary#53]
In Framework 4.7.1 function ImageFile.FromFile() throw Exception Cannot find file

**Comment by oozcitak** [comment]
That is not much to go on. Are you sure the file actually exists? Can you post some source code?

**Comment by fialot** [comment]
I tried compiling  the same program with Framework 4.7.1 on another PC and everything was OK. 
Maybe an outdated libraries somewhere in windows 10... Sorry for fake alarm.

**Comment by oozcitak** [comment]
NP
