### ISSUE TITLE
Load image exception

### ISSUE THREAD

**Issue by bednart** [oozcitak/exiflibrary#54]
Hi,
I'm trying to load JPG file attached below using ImageFile.FromFile and it fails on exception **Source array was not long enough. Check srcIndex and length, and the array's lower bounds.** There is no problem for other JPG files but this is one of few which fails. Could you please check it what is wrong?

Thanks,
Tomas

![test](https://user-images.githubusercontent.com/10383704/39524627-d3748c16-4e19-11e8-8171-d2a9a8a1b13e.jpg)

**Comment by oozcitak** [comment]
I don't get any exceptions with the image you sent. But it is probably re-encoded when you uploaded it to github. Can you send me the image in a zip file? My email is in source file headers.

**Comment by bednart** [comment]
Here it is: [test.zip](https://github.com/oozcitak/exiflibrary/files/1970255/test.zip)

Stack trace:
`   in System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   v System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   v ExifLibrary.BitConverterEx.CheckData(Byte[] value, Int64 startIndex, Int64 length, ByteOrder from, ByteOrder to)
   v ExifLibrary.BitConverterEx.ToUInt32(Byte[] value, Int64 startIndex, ByteOrder from, ByteOrder to)
   v ExifLibrary.BitConverterEx.ToUInt32(Byte[] value, Int64 startIndex)
   v ExifLibrary.JPEGFile.ReadExifAPP1()
   v ExifLibrary.JPEGFile..ctor(Stream stream, Encoding encoding)
   v ExifLibrary.ImageFile.FromStream(Stream stream, Encoding encoding)
   v ExifLibrary.ImageFile.FromFile(String filename, Encoding encoding)
   v ExifLibrary.ImageFile.FromFile(String filename)`

**Comment by bednart** [comment]
Thanks a lot. It works 👍
