### ISSUE TITLE
Add native async support

### ISSUE THREAD

**Issue by roryap** [oozcitak/exiflibrary#63]
Do you have any plans to add native async support to your product?  It can take a noticeably-long time to load the image data for a list of files.

**Comment by oozcitak** [comment]
Can you please clarify? You can already use the library asynchronously.

**Comment by roryap** [comment]
Can you show me the methods that are natively asynchronous, i.e. that use the I/O hardware to perform the async work, freeing up my threads for other work?  Or are you referring to the fact that I can just call your methods from a background thread? -- which isn't true async, it's "sync over async" because it's just blocking a background thread and thus reducing the number of threads in the thread pool that are available for other operations.

**Comment by oozcitak** [comment]
No, there are currently no _async_ versions of the functions exported by the library. I'll take a look at the I/O bound parts of the library and offer such functions.

**Comment by oozcitak** [comment]
Just released [`v1.2.35`](https://www.nuget.org/packages/ExifLibNet/1.2.35) with async methods. I'd appreciate any feedback you can provide.
