### ISSUE TITLE
Orientation values 5-8 are wrong

### ISSUE THREAD

**Issue by PredatH0r** [oozcitak/exiflibrary#65]
The correct rotation values are explained here: 
https://www.impulseadventure.com/photo/exif-orientation.html 
https://stackoverflow.com/questions/20600800/js-client-side-exif-orientation-rotate-and-mirror-jpeg-images.
These values are consistent with the output of my Samsung cell phone cameras (S3, xcover3, J7).

In ExifLibrary.Orientation the values 1-4 are assigned to the correct names, but 5-8 are wrong.
It should be:
RotatedLeftAndMirrored = 5,
RotatedLeft = 6,
RotatedRightAndMirrored=7,
RotatedRight=8

I also stumbled across web pages with inconsistent/wrong explanations, like on the bottom of https://sirv.com/help/resources/rotate-photos-to-be-upright/

**Comment by oozcitak** [comment]
Thank you. Fixing and adding test cases for all eight orientations.
