### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by JojoShow** [oozcitak/exiflibrary#66]
Hello,

Trying to change the date property of a jpeg file. I got an ArgumentException: An item with the same key has already been added.". I thought I was misusing ExifLibrary so I downloaded the source project and tried to open my image in "ExifTest.exe" => same result. When I open the file it ends up by crashin in "WriteExifApp1" with the same ArgumentException.

My jpg file is just a photo, shot using my cell phone, not modified at all and its properties are well displayed by both my Windows OS and My Android OS. 

If it may hep the file can be found here: [https://1drv.ms/f/s!Aqcd8QCoR1WCqHeeL-BE3aH-yclW]

Jérôme

**Comment by oozcitak** [comment]
The image above shows no errors on my end. But it is probably re-encoded when uploaded. Can you please send the image in a zip file? So that I receive the original image.

**Comment by JojoShow** [comment]
I've set the zipped image here:
[https://1drv.ms/u/s!Aqcd8QCoR1WCqHmeL-BE3aH-yclW](url)

**Comment by oozcitak** [comment]
Can you send your code too, please?

**Comment by JojoShow** [comment]
I'm using a WinForm project .NET Framework 4.7.2 and using a simple button click to test modifying date.
Here's the "OnClick" button code

`		private void Button1_Click(object sender, EventArgs e)
		{
			try
			{
				var originalDateTime = new DateTime(2019, 12, 07, 19, 34, 35, DateTimeKind.Local);
				var modifiedDateTime = new DateTime(2019, 11, 07, 19, 34, 35, DateTimeKind.Local);

				var testImagePath = Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location), "IMG_20191207_193435.jpg");
				var file = ImageFile.FromFile(testImagePath);

				file.Properties.ToList().ForEach(p => Trace.WriteLine($"{p.Name}: {p.Value}"));

				var groups = file.Properties.GroupBy(p => p.IFD).Where(g => g.Count() > 1).ToList();
				groups.ForEach(g => Trace.WriteLine(g.Key));

				var dateTimeProperty = file.Properties.FirstOrDefault(p => p.Name == "DateTime");

				if (dateTimeProperty?.Value is DateTime dt)
				{
					if (dt.Date == originalDateTime.Date)
					{
						dateTimeProperty.Value = modifiedDateTime;
					}
					else
					{
						dateTimeProperty.Value = originalDateTime;
					}
				}

				file.Save(testImagePath);
			}
			catch (Exception ex)
			{
				MessageBox.Show(ex.ToString());
			}
		}
`
