### ISSUE TITLE
When ı am getting aperturevalue(fnumber) of photograph return different values

### ISSUE THREAD

**Issue by fatihyvg** [oozcitak/exiflibrary#81]
ı am getting aperturevalue of photograph Fnumber value but return 11/5 as values  how  can ı convert to e.g f2.8 value
my code
ImageFile img = ImageFile.FromStream("photo.jpg"));
object values = img.Properties.Get<ExifProperty>(ExifTag.FNumber); 
string res = Convert.ToString(values);
result e.g return 11/5 like values
https://ibb.co/VC7bt09

**Comment by oozcitak** [comment]
Did you try: `img.Properties.Get<ExifURational>(ExifTag.FNumber);`

**Comment by fatihyvg** [comment]
çok teşekkürler sorunum çözüldü...
