### ISSUE TITLE
Incorrect type casting in docs

### ISSUE THREAD

**Issue by MenachemICTBIT** [oozcitak/exiflibrary#86]
In multiple places in the docs there is an incorrect casting

For example:

`file.Set(ExifTag.ISOSpeedRatings, <ushort>200);` is incorrect

Should be `file.Set(ExifTag.ISOSpeedRatings, (ushort)200);`

**Comment by bugybunny** [comment]
I was fixing something else in the documentation and created a PR for this and also fixed the one cast in the file I touched https://github.com/oozcitak/exiflibrary/pull/92. This project seems kind of dead though; not sure if the maintainer will see and merge it.
